steps:
  # Build Backend
  - id: "build-backend"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west8-docker.pkg.dev/$PROJECT_ID/dental-containers/backend:$COMMIT_SHA", ".", "-f", "Dockerfile", "--target", "backend-runner"]
  
  # Push Backend
  - id: "push-backend"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west8-docker.pkg.dev/$PROJECT_ID/dental-containers/backend:$COMMIT_SHA"]

  # Build Frontend
  - id: "build-frontend"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west8-docker.pkg.dev/$PROJECT_ID/dental-containers/frontend:$COMMIT_SHA", ".", "-f", "Dockerfile", "--target", "frontend-runner"]

  # Push Frontend
  - id: "push-frontend"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west8-docker.pkg.dev/$PROJECT_ID/dental-containers/frontend:$COMMIT_SHA"]

  # Deploy Backend
  - id: "deploy-backend"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args: ["run", "deploy", "dental-saas-backend", "--image", "europe-west8-docker.pkg.dev/$PROJECT_ID/dental-containers/backend:$COMMIT_SHA", "--region", "europe-west8", "--platform", "managed", "--allow-unauthenticated", "--set-env-vars=DATABASE_URL=$$DATABASE_URL,JWT_SECRET=$$JWT_SECRET,GCP_BUCKET_NAME=$$GCP_BUCKET_NAME,GCP_PROJECT_ID=$$GCP_PROJECT_ID"]
    secretEnv: ["DATABASE_URL", "JWT_SECRET", "GCP_BUCKET_NAME", "GCP_PROJECT_ID"]

  # Deploy Frontend
  - id: "deploy-frontend"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args: ["run", "deploy", "dental-saas-frontend", "--image", "europe-west8-docker.pkg.dev/$PROJECT_ID/dental-containers/frontend:$COMMIT_SHA", "--region", "europe-west8", "--platform", "managed", "--allow-unauthenticated", "--set-env-vars=NEXT_PUBLIC_API_URL=https://dental-saas-backend-run-url"]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
    env: "DATABASE_URL"
  - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
    env: "JWT_SECRET"
  - versionName: projects/$PROJECT_ID/secrets/GCP_BUCKET_NAME/versions/latest
    env: "GCP_BUCKET_NAME"
  - versionName: projects/$PROJECT_ID/secrets/GCP_PROJECT_ID/versions/latest
    env: "GCP_PROJECT_ID"
